version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./datasets:/usr/src/app/datasets/

