version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: 'always'
    ports:
        - "5432:5432"
    volumes:
      - './databese:/var/lib/postgresql/data/'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./datasets:/usr/src/app/datasets/
    depends_on:
      - db

