version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: 'always'
    ports:
        - "5432:5432"
    volumes:
      - './database:/var/lib/postgresql/data/'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app_postgres
    volumes:
      - ./datasets:/home/app_user/datasets
    depends_on:
      - db
    stdin_open: true
    tty: true

